version: '3.8'

services:
  notification-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
      - SERVER_PORT=8080
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=rantipaydb
      - DB_SCHEMA=notification_service
      - JWT_SECRET=your-secret-key
      - BUSINESS_SERVICE_GRPC_ADDRESS=business-service:50051
      - METRICS_ENABLED=true
      - METRICS_PORT=9090
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - notification-network

  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rantipaydb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - notification-network

  # Cliente simulado para el servicio de negocio
  business-service-mock:
    image: mockserver/mockserver:latest
    ports:
      - "50051:50051"
    environment:
      - MOCKSERVER_SERVER_PORT=50051
    networks:
      - notification-network

  # Herramientas de monitoreo
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - notification-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - notification-network

networks:
  notification-network:
    driver: bridge

volumes:
  postgres-data:
  grafana-data: